/*
 * File: ScreenDisplayDeviceCommandList.h
 * Author: fascio
 * 
 * Created on November 21th, 2014, 15:07
 */ 
 
#ifndef __SCREEN_DISPLAY_DEVICE_COMMAND_LIST_H__
#define __SCREEN_DISPLAY_DEVICE_COMMAND_LIST_H__


#define SCREEN_DISPLAY_DEVICE_MASTER_COMMAND_ID_LED_STATUS			 (1001)
#define SCREEN_DISPLAY_DEVICE_SLAVE_COMMAND_ID_LED_STATUS			 (2001)



#endif /* __SCREEN_DISPLAY_DEVICE_COMMAND_LIST_H__ */
